
<?php include('includes/Header.php') ?>

<a class="btn right black" href="<?= '../stamps'; ?>">Go back </a>
   
    <!-- Section: Follow-->
    <section class="section section-follow black darken-2 white-text center">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <h4>Follow Us</h4>
                    <p>Follow us in social media</p>
                    <a href="https://www.facebook.com/" target=" _blank " class="black-text ">
                        <i class="fab fa-facebook fa-4x "></i>
                    </a>
                    <a href="https://twitter.com " target="_blank " class="black-text ">
                        <i class="fab fa-twitter fa-4x "></i>
                    </a>
                    <a href="https://linkedin.com " target="_blank " class="black-text ">
                        <i class="fab fa-linkedin fa-4x "></i>
                    </a>
                    <a href="https://googleplus.com " target="_blank " class="black-text ">
                        <i class="fab fa-google-plus fa-4x "></i>
                    </a>
                    <a href="https://pinterest.com " target="_blank " class="black-text ">
                        <i class="fab fa-pinterest fa-4x "></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Section: About -->
    <section id="about" class="section section-about grey lighten-3 center scrollspy">
        <div class="container">
            <h2>About Stamps Collection</h2>
            <p class="flow-text">Stamps Collection </p>
            <div class="row">
                <div class="col s12 m6">
                    <img src="images/usa.jpg" alt="" class="responsive-img circle">
                    <h4 class="blue-text"></h4>
                </div>

                <div class="col s12 m6">
                    <div class="parrafo">
                        <h3>Welcome :)</h3>
                        <em>
                            <strong>Stamps Collection</strong> Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis
                            accusantium
                            repudiandae architecto sequi, amet aliquid!
                        </em>
                        <br><br>
                        <p>
                            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum accusamus error numquam pariatur
                            quidem, provident sequi cum culpa eveniet atque alias beatae dolorem rem aliquid eum nisi repellat
                            vitae
                            quibusdam unde labore eaque esse accusantium? Repellat, dolorum illo fuga voluptates neque inventore
                            eos
                            officiis porro, velit adipisci natus aliquid facere!
                        </p>

                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci fugit eligendi architecto hic
                            reiciendis quaerat ullam dolores aliquid facilis, incidunt ab dignissimos? Non, doloremque asperiores
                            ad
                            debitis pariatur cumque dolorem! Tempore, hic similique. Voluptates sunt nisi non, et veritatis quam
                            consectetur aperiam eos nesciunt dolorum accusantium, in, aut doloremque repellendus?
                        </p>
                        <aside>
                            <blockquote>Denis Sanchez Leyva</blockquote>
                        </aside>

                        <br>
                        <br>
                    </div>
                </div>

    </section>


    <?php include 'includes/Footer.php' ?>
   




    