
<?php include('includes/Header.php') ?>


<!-- Section: Contact-->

<section id="contact" class="section section-contact scrollspy">

<a class="btn right black" href="<?= '../stamps'; ?>">Go back </a>

<div class="container">
    <div class="row">
        <div class="col s12 m6">
            <div class="card-panel black white-text center">
                <i class="material-icons medium">email</i>
  
                <h5>Contact</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias dolores libero magnam quas
                    exercitationem accusantium.</p>
            </div>
            <ul class="collection with header">
                <li class="collection-header">
                    <h4>Location</h4>
                </li>
                <li class="colletion-item">Stamps Collection</li>
                <li class="colletion-item">Address:</li>
                <li class="colletion-item">Doral</li>
                <li class="colletion-item">Phone: 786-122-5696 </li>
                <li class="colletion-item">Email: Stamps Collection@gmail.com</li>
                <li class="colletion-item">Miami Dade.33176</li>
            </ul>
        </div>
        <div class="col s12 m6">
            <div class="card-panel grey lighten-3">
                <h5>Please fill this form bellow</h5>

                <form id="form" action="">
                    <div class="input-field">
                        <input type="text" placeholder="Nombre" id="name" value=''>
                        <label for="name" id="name"></label>
                    </div>
                    <div class="input-field">
                        <input type="email" placeholder="Email" id="email">
                        <label for="email"></label>
                    </div>
                    <div class="input-field">
                        <input type="text" placeholder="Telefono" id="phone">
                        <label for="phone"></label>
                    </div>

                    <div class="input-field">
                        <textarea placeholder="Enter Mensaje " id="message"> </textarea>
                        <label for="message">Message</label>
                    </div>

                    <input type="submit" value="Submit" class="btn blue" id="btn">
                </form>
            </div>
        </div>
    </div>
</div>
</section>


<?php include('includes/Footer.php') ?>

